config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :registrations => "registrations" } 

mount Ckeditor::Engine => '/ckeditor'

get 'sitemap' => 'sitemap#index'

get 'blogs' => 'blogs#index', as: :blogs
get 'blogs/new' => 'blogs#new', as: :new_blog
post 'blogs' => 'blogs#create'

get ':blog_id' => 'blogs#show', as: :blog
get ':blog_id/edit' => 'blogs#edit', as: :edit_blog
patch ':blog_id' => 'blogs#update'
put ':blog_id' => 'blogs#update'
delete ':blog_id' => 'blogs#destroy'

# Routes about TAGS
post ':blog_id/tags/tagtool' => 'tags#tagtool'
get ':blog_id/tags' => 'tags#index', as: :blog_tags
post ':blog_id/tags' => 'tags#create'
get ':blog_id/tags/:word' => 'tags#show', as: :blog_tag
post ':blog_id/tags/:word' => 'tags#update'
delete ':blog_id/tags/:word' => 'tags#destroy'

get ':blog_id/posts' => 'posts#index', as: :blog_posts
get ':blog_id/posts/new' => 'posts#new', as: :new_post
post ':blog_id/posts' => 'posts#create'

get ':blog_id/:post_id' => 'posts#show', as: :blog_post
get ':blog_id/:post_id/edit' => 'posts#edit', as: :edit_blog_post
patch ':blog_id/:post_id' => 'posts#update'
put ':blog_id/:post_id' => 'posts#update'
delete ':blog_id/:post_id' => 'posts#destroy', as: :destroy_blog_post


# You can have the root of your site routed with "root"
root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post
	include Mongoid::Document
	field :_id, type: String, default: ->{ textid }
	field :title, type: String
  field :content, type: String
  field :textid, type: String
  field :date, type: DateTime, default: ->{ Date.today }
  field :published, type: Boolean
	embeds_many :comments
	has_and_belongs_to_many :tags
	belongs_to :blog
  before_validation :generate_textid
	validates_uniqueness_of :textid

	
	def generate_textid
	  require "i18n"
    unless self.textid?
      textid=I18n.transliterate(self.title).downcase.tr(' ','-').tr('^a-z0-9-', '').gsub(/^-/,'').gsub(/-*$/,'')
      self._id=textid
      self.textid=textid
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    logger.debug(params)
    # Index list posts
    @blog = Blog.find(params[:blog_id])
    @posts = @blog.posts
    
    authorize @posts
    
    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end
  
  def show
    @blog = Blog.find(params[:blog_id])  
    @post = @blog.posts.find(params[:post_id])
    
    authorize @post
    
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  # Get /:blogtextid/new
  def new
    @blog = Blog.find(params[:blog_id])
    @post = @blog.posts.new
    
    authorize @post
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # Get /:blogtextid/:posttextid/edit
  def edit
    @blog = Blog.find(params[:blog_id])
    @post = @blog.posts.find(params[:post_id])

    authorize @post

  end

  # POST /:blogtextid
  # POST /:blogtextid.json
  def create
    @blog = Blog.find(params[:blog_id])
    @post = @blog.posts.new(post_params)
    
    authorize @post
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to  blog_post_path(@blog, @post), notice: 'Post created' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

    @post.save
  end

  # PUT /:blogtextid/:posttextid
  # PUT /:blogtextid/:posttextid.json
  def update
    @blog = Blog.find(params[:blog_id])
    @post = @blog.posts.find(params[:post_id])
    
    authorize @post
    
    respond_to do |format|
      if @post.update_attributes(post_params)
        format.html { redirect_to( blog_post_path(@blog, @post) ,notice: 'Post was modified') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    blog = Blog.find(params[:blog_id])
    post = blog.posts.find(params[:post_id])
    authorize post
    post.destroy
    redirect_to( blog_path(blog) ,notice: 'Post deleted')
  end

  private
  def post_params
    params.require(:post).permit(:textid, :title, :content, :date, :published)
  end
  
end

app/views/posts/_form.html.erb
<%= form_for [@blog, @post], :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this hub from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.cktext_area :content, :value => @post.content, :id => 'contentarea'  %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_field :date, :class => 'datetimepicker' %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<h3><%= post.title %></h3>
<div class="postcontent"><%= post.content.html_safe %></div>
<p><%= post.date %></p>

app/views/posts/_postslist.html.erb
<% @posts.each do |p| %>
	<article class="blogpost">
		
		<header class="posthead">
			<h2 class="subheader"><%= link_to(p.title, blog_post_path(@blog,p)) %></h1>
				<div class="articlemetadata"><span><%= time_tag p.date %></span>
					 <% if p.tags.size != 0 %>
					 <span> | </span>
					 Tags :   
						<% p.tags.each do |t| %>
							<%= link_to t.word,blog_tag_path(@blog,t) %>
						<% end %>
					<% end %>
				</div>
		</header>
		
		<%= Nokogiri::HTML.parse(p.content).css('p').first.to_s.html_safe %>
		
		<footer class="postfoot">
			<div class="postfootreadmore">
			<%= link_to("Read more...", blog_post_path(@blog,p), html_options = {:class => 'button tiny secondary'}) %>
			</div>
		</footer>
	</article>
<%end%>
<% if @nbpages>1 %>
<ul class="pagination">
	<% if (@page.to_i!=1) %> <li class="arrow"> <%= link_to("<", url_options = {:data => {:page => @page.to_i-1}}) %> </li> <% end %>
	<% (1..@nbpages).each do |page| %>
		<li class="<%= 'current' if (@page.to_s==page.to_s) %>"> <%= link_to(page, url_options = {:data => {:page => page}}, html_options = {:class => (page==@page) ? nil : 'current'} )%> </li>
	<% end %>
	 <% if (@page.to_i!=@nbpages.to_i ) %> <li class="arrow"> <%= link_to(">", url_options = {:data => {:page => @page.to_i+1}}) %> </li> <%end%>
</ul>
<% end %>

app/views/posts/edit.html.erb
<h1> Edition post </h1>

<%= render 'form' %>

<%= link_to "Show", blog_post_path(@blog, @post) %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>textid</th>
    <th>Title</th>
    <th>Published</th>
    <th>DateTime</th>
    <th>Actions</th>
  </tr>

<% @posts.each do |p| %>
  <tr>
    <td><%= p.textid %></td>
    <td><%= link_to p.title, blog_post_path(@blog,p) %></td>
    <td><%= p.published.to_s %></td>
    <td><%= p.date %></td>
    <td><%= link_to 'Edit', edit_blog_post_path(@blog,p) %>
    <%= link_to 'Destroy', destroy_blog_post_path(@blog,p), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class='row'>
	<div id="postslist" class='columns small-9'>
	<article>
		<header>
			<h1><%= @post.title %></h1>
			<div class="articlemetadata"><span><%= time_tag @post.date %></span>
				 <% if @post.tags.size != 0 %>
				 <span> | </span>
				 Tags :   
					<% @post.tags.each do |t| %>
						<%= link_to t.word,blog_tag_path(@blog,t) %>
					<% end %>
				<% end %>
			</div>
		</header>
		
		<%= @post.content.html_safe%>
		
		<% if @post.comments.size != 0 %>
			<h2>Comments</h2>
			<ul>
			<% @post.comments.each do |c| %>
				<li><%= c.content %></li>
			<% end %>
			</ul>
		<% end %>
		
		<footer>
		</footer>
	</article>
	</div>
	<div id="postsinfo" class='columns small-3'>
		<%= render "layouts/rightcolumn" %>
	</div>
</div>