config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :registrations => "registrations" } 

mount Ckeditor::Engine => '/ckeditor'

get 'sitemap' => 'sitemap#index'

get 'blogs' => 'blogs#index', as: :blogs
get 'blogs/new' => 'blogs#new', as: :new_blog
post 'blogs' => 'blogs#create'

get ':blog_id' => 'blogs#show', as: :blog
get ':blog_id/edit' => 'blogs#edit', as: :edit_blog
patch ':blog_id' => 'blogs#update'
put ':blog_id' => 'blogs#update'
delete ':blog_id' => 'blogs#destroy'

# Routes about TAGS
post ':blog_id/tags/tagtool' => 'tags#tagtool'
get ':blog_id/tags' => 'tags#index', as: :blog_tags
post ':blog_id/tags' => 'tags#create'
get ':blog_id/tags/:word' => 'tags#show', as: :blog_tag
post ':blog_id/tags/:word' => 'tags#update'
delete ':blog_id/tags/:word' => 'tags#destroy'

get ':blog_id/posts' => 'posts#index', as: :blog_posts
get ':blog_id/posts/new' => 'posts#new', as: :new_post
post ':blog_id/posts' => 'posts#create'

get ':blog_id/:post_id' => 'posts#show', as: :blog_post
get ':blog_id/:post_id/edit' => 'posts#edit', as: :edit_blog_post
patch ':blog_id/:post_id' => 'posts#update'
put ':blog_id/:post_id' => 'posts#update'
delete ':blog_id/:post_id' => 'posts#destroy', as: :destroy_blog_post


# You can have the root of your site routed with "root"
root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_rightcolumn.html.erb
	<h2>Recent posts</h2>
		<% @blog.posts.where({ published: true }).sort(date: -1).limit(5).each do |p| %>
			<%= link_to(p.title, blog_post_path(@blog,p)) %> <br />
		<% end %>
		<hr />
	<h2>Tags</h2>
		<%= render "tags/tagtool"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield :title || Amber::Application.config.shorttitle %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
</head>
<body>
<% if (defined? @blog) %>
<script type="text/javascript" charset="utf-8">
	var ROOT_PATH = '<% if @blog.textid? %><%= blog_path %><% end %>';
</script>
<% end %>

<nav class="top-bar" data-topbar>
	<ul class="title-area"> <li class="name" class="active"> <h1><a href="/"><%= Amber::Application.config.shorttitle %></a></h1> </li>
		<li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li> 
	</ul> 
	<section class="top-bar-section"> <!-- Right Nav Section --> 
			<ul class="left">
				<% Blog.each do |b| %>
					<% if b.published? %>
						<li><%= link_to b.title,b %></li>
					<% end %>
				<% end %>
			</ul>
	</section>
	<section class="top-bar-section"> <!-- Right Nav Section --> 
			<ul class="right">
	<% if user_signed_in? %>
	  	<li><%= link_to  current_user.email, edit_user_registration_path, :class => 'navbar-link' %></li>
  		<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
	<% else %>
		<% if Amber::Application.config.autosubscribe %>
  		<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
		<% end %>
  		<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
	<% end %>
	</ul>
	</section>	
</nav>

<div class='row'>
<div class='columns small-12 large-12'>
<% if alert %>
<div data-alert class="alert-box alert radius"> <%= alert %> </div>
<% end %>
<% if notice %>
<div data-alert class="alert-box info radius"> <%= notice %> </div>
<% end %>
</div>

<div class='columns small-12 large-12'>
<%= yield %>
</div>

</body>
</html>